#!/bin/bash

cd ../db

for dir in $(find * -type d)
do
  (
    cd $dir
    for file in *
    do
      if [ "$file" != "$index" ]
      then
        title=$(head -1 $file)
        echo "$file $title"
      fi
    done
    cd - &> /dev/null
  ) > $dir.index
done
