#!/bin/bash

cd ../db
rm -f *.index

for dir in $(find * -maxdepth 0 -type d)
do
  (
    cd $dir
    for file in $(find * -type f \! -name '*~*')
    do
      title=$(head -1 $file)
      headers=$(sed '2!d' $file)

      if [[ "$headers" =~ "*" ]]
      then
        headers=${headers//\*/}
      else
        headers=
      fi
      echo "$dir/$file $title # $headers"
    done
    cd - &> /dev/null
  ) > $dir.index
  echo "$dir.index" >> db.index
done
